<a href="https://colab.research.google.com/github/Niktain-america/Project-Portfolio/blob/main/Python_Part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import seaborn as sns

In [ ]:
pd.merge?

In [ ]:
# Let's define a few toy datasets to use as examples

df0 = DataFrame({'key': ['a', 'a', 'c', 'd', 'e'], 'data0': np.random.randint(0, 100, 5)})
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': np.random.randint(0, 100, 7)})
df2 = DataFrame({'key': ['a', 'b', 'd', 'f', 'g'], 'data1': np.random.randint(0, 100, 5)})

df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data3': np.random.randint(0, 100, 7)})
df4 = DataFrame({'rkey': ['a', 'b', 'd'], 'data4': np.random.randint(0, 100, 3)})

In [ ]:
df0

  key  data0
0   a     98
1   a     51
2   c     37
3   d     35
4   e     28

In [ ]:
df1

  key  data1
0   b     37
1   b     58
2   a     12
3   c     99
4   a     51
5   a     74
6   b     42

In [ ]:
#Default merge with no parameter

pd.merge(df0, df1, on='key', how='inner')

# We see that its an inner join by default (output key is the intersection of input keys)
# Merge happens on the column 'key' which is common to both datasets;
    # We could've written pd.merge(df1, df2, on='key', how='inner') to the same effect

  key  data0  data1
0   a     98     12
1   a     98     51
2   a     98     74
3   a     51     12
4   a     51     51
5   a     51     74
6   c     37     99

In [ ]:
#outer join
pd.merge(df0, df2, on='key', how='outer')

  key  data0  data1
0   a   98.0   21.0
1   a   51.0   21.0
2   c   37.0    NaN
3   d   35.0   32.0
4   e   28.0    NaN
5   b    NaN    4.0
6   f    NaN   47.0
7   g    NaN    9.0